// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewUser struct {
	FirstName      string  `json:"firstName"`
	LastName       string  `json:"lastName"`
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	OrganisationID *string `json:"organisationId"`
}

type Token struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiredAt    int    `json:"expiredAt"`
}

type User struct {
	ID             string  `json:"id"`
	FirstName      string  `json:"firstName"`
	LastName       string  `json:"lastName"`
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	OrganisationID *string `json:"organisationId"`
	CreatedAt      int     `json:"created_at"`
	UpdatedAt      *int    `json:"updatedAt"`
	Disabled       *bool   `json:"disabled"`
	Role           *int    `json:"role"`
}
